version: '3.8'

services:
  web:
    build: .
    container_name: banking-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - banking-net

  db:
    image: mysql:8.0
    container_name: banking-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_service
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - banking-net

networks:
  banking-net:

volumes:
  db-data:
